scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    info.changeScoreBy(1)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.y += -30
})
scene.onHitWall(SpriteKind.Enemy, function (sprite, location) {
    sprites.destroy(sprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    game.setGameOverScoringType(game.ScoringType.HighScore)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairSouth, function (sprite, location) {
    directions = true
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    mySprite.sayText("Oww", 500, false)
    info.changeLifeBy(-1)
})
let myEnemy: Sprite = null
let mySprite: Sprite = null
let directions = false
directions = false
tiles.setCurrentTilemap(tilemap`level1`)
scene.setBackgroundColor(13)
// Main program
let list = [assets.image`myCat`, assets.image`mySnake`, assets.image`myShroom`]
mySprite = sprites.create(list.removeAt(randint(0, list.length - 1)), SpriteKind.Player)
info.setLife(5)
scene.cameraFollowSprite(mySprite)
tiles.placeOnTile(mySprite, tiles.getTileLocation(0, 6))
game.onUpdate(function () {
    mySprite.ay = 180
})
game.onUpdate(function () {
    if (directions) {
        controller.moveSprite(mySprite)
    } else {
        controller.moveSprite(mySprite, 100, 0)
    }
})
game.onUpdateInterval(3000, function () {
    myEnemy = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        ...........ff...........
        .........ffffff.........
        ..........ffff..........
        ...........ff...........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(myEnemy, tiles.getTileLocation(25, 0))
    myEnemy.ay = 240
})
game.onUpdateInterval(3000, function () {
    for (let value of tiles.getTilesByType(sprites.builtin.forestTiles0)) {
        myEnemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ...........ff...........
            ..........ffff..........
            .........ffffff.........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ........................
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        tiles.placeOnTile(myEnemy, value)
        myEnemy.ay = -240
    }
})
game.onUpdateInterval(3000, function () {
    myEnemy = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ...f33333333333333ffff..
        ...f33f33f3f3333f3f.....
        ...f3333333333f333ffff..
        ...f33f3f33f333333f.....
        ...f3333333333f3f3ffff..
        ...f33333f333333333.....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(myEnemy, tiles.getTileLocation(25, 0))
    myEnemy.ay = 240
})
