controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.y += -30
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    game.setGameOverScoringType(game.ScoringType.HighScore)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite, location) {
    info.changeScoreBy(1)
    tiles.setTileAt(location, assets.tile`transparency16`)
})
let myEnemy: Sprite = null
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
scene.setBackgroundColor(13)
// Main program
let list = [assets.image`myCat`, assets.image`mySnake`, assets.image`myShroom`]
mySprite = sprites.create(list.removeAt(randint(0, list.length - 1)), SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
tiles.placeOnTile(mySprite, tiles.getTileLocation(0, 6))
controller.moveSprite(mySprite, 100, 0)
game.onUpdate(function () {
    mySprite.ay = 180
})
game.onUpdateInterval(500, function () {
    for (let value of tiles.getTilesByType(sprites.builtin.forestTiles4)) {
        myEnemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            ...........ff...........
            .........ffffff.........
            ..........ffff..........
            ...........ff...........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        tiles.placeOnTile(myEnemy, value)
        myEnemy.ay = -240
    }
    sprites.destroy(myEnemy)
})
